server {
    listen 80;
    server_name localhost;

    # Frontend Angular (Archivos estáticos)
    location / {
        root /var/www/frontend; # Ruta genérica, ajustar en Unidad 2
        try_files $uri $uri/ /index.html;
    }

    # API Inventario
    location /api/inventario/ {
        # Configuración para proxy pass a Laravel
        # En producción o con Docker, esto apuntará al contenedor de PHP/Laravel
        proxy_pass http://127.0.0.1:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
